// Part 2: Lessons 17-32 (48 puzzles, 3 per lesson)
// Covers: functions, until loops, conditionals, logic operators, arrays, penguins

const part2 = [

  // =====================================================
  // LESSON 17: Function Farm (functions, grab, drop)
  // =====================================================

  {
    id: 1,
    part: 2,
    lesson: 17,
    lessonTitle: 'Function Farm',
    title: 'Pick and Place',
    concept: 'grab() / drop()',
    gridWidth: 7,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'banana', x: 3, y: 1 },
      { type: 'pile', x: 6, y: 1 },
    ],
    autoGrab: false,
    starterCode: '# Walk to the banana, grab it, carry it!\n# New commands: grab() and drop()\nstep 3\ngrab()\n# Now step to the pile and drop()\n',
    hint: 'After grab(), step 3 more to reach the pile, then use drop() to place the banana.',
    starThresholds: [5, 4, 4],
    requiredCommands: ['grab', 'drop'],
    lessonContent: '<h3>Functions</h3><p>A <b>function</b> is a set of instructions that performs a specific task. You\'ve been using functions like <code>step</code> and <code>turn</code>. Now you\'ll learn to <b>define</b> your own!</p><p>New commands: <code>grab()</code> picks up the item you\'re standing on. <code>drop()</code> places it down.</p><p>To define a function:</p><pre>myFunc = () ->\n  step 2\n  turn right</pre><p>Then call it: <code>myFunc()</code></p>',
  },

  {
    id: 2,
    part: 2,
    lesson: 17,
    lessonTitle: 'Function Farm',
    title: 'Two Deliveries',
    concept: 'defining functions',
    gridWidth: 9,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 1 },
      { type: 'pile', x: 4, y: 1 },
      { type: 'banana', x: 6, y: 1 },
      { type: 'pile', x: 8, y: 1 },
    ],
    autoGrab: false,
    starterCode: '# Define a function to deliver!\ndeliver = () ->\n  step 2\n  grab()\n  step 2\n  drop()\n# Call it twice:\n',
    hint: 'The deliver function steps to a banana, grabs it, steps to a pile, and drops it. Call it twice: deliver() then deliver().',
    starThresholds: [8, 6, 4],
    requiredCommands: ['->'],
  },

  {
    id: 3,
    part: 2,
    lesson: 17,
    lessonTitle: 'Function Farm',
    title: 'Goto Function',
    concept: 'function parameters',
    gridWidth: 8,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'banana', x: 3, y: 2 },
      { type: 'banana', x: 3, y: 4 },
      { type: 'banana', x: 7, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# A function with a parameter!\n# goto = (a) ->\n#   turnTo a\n#   step distanceTo a\n# Call it for each banana:\n# goto bananas[0]\n',
    hint: 'Define goto with parameter a. Inside: turnTo a, step distanceTo a. Then call goto for each banana. Route: right to (3,2), down to (3,4), right to (7,4).',
    starThresholds: [10, 8, 5],
    requiredCommands: ['->'],
    assessments: [
      { type: 'multiple-choice', question: 'What does grab() do?', options: ['Moves the monkey forward', 'Picks up the item you\'re standing on', 'Creates a new banana', 'Turns the monkey around'], correct: 1 },
      { type: 'multiple-choice', question: 'How do you define a function called "fetch" with parameter "x"?', options: ['fetch x ->', 'fetch = (x) ->', 'function fetch(x)', 'def fetch x'], correct: 1 },
      { type: 'true-false', question: 'A function definition runs immediately when the code starts.', correct: false, feedback: 'A function only runs when you CALL it in your code!' },
    ],
  },

  // =====================================================
  // LESSON 18: Fun-ctions! (debugging, step -x, for+functions)
  // =====================================================

  {
    id: 4,
    part: 2,
    lesson: 18,
    lessonTitle: 'Fun-ctions!',
    title: 'Backtrack',
    concept: 'step -x',
    gridWidth: 7,
    gridHeight: 1,
    monkeyStart: { x: 3, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 5, y: 0 },
      { type: 'banana', x: 1, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Use step with negative numbers to go backward!\nstep 2\n# Now go backward to get the other banana\n# step -4 moves 4 squares backward\n',
    hint: 'step 2 gets the right banana. Then step -4 goes backward to get the left one.',
    starThresholds: [3, 2, 2],
    lessonContent: '<h3>More About Functions</h3><p>You can use <b>negative numbers</b> with step: <code>step -3</code> moves backward 3 squares.</p><p><b>Debugging</b> means finding and fixing mistakes in code. Read code slowly and carefully!</p><p>You can also put <b>for loops inside functions</b>:</p><pre>zigzag = () ->\n  for i in [1..3]\n    step 1\n    turn right\n    step 1\n    turn left</pre>',
  },

  {
    id: 5,
    part: 2,
    lesson: 18,
    lessonTitle: 'Fun-ctions!',
    title: 'Debug This!',
    concept: 'debugging',
    gridWidth: 5,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 4, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# This code has bugs! Fix them:\nstep 4\nturn right\nstep 3\n# Hint: the monkey needs to reach (4,4)\n',
    hint: 'Run the code and watch the monkey. After step 4 and turn right, how many more steps to row 4? It should be step 4, not step 3!',
    starThresholds: [4, 3, 3],
  },

  {
    id: 6,
    part: 2,
    lesson: 18,
    lessonTitle: 'Fun-ctions!',
    title: 'Loop Function',
    concept: 'for loop + function',
    gridWidth: 9,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 0 },
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 6, y: 0 },
      { type: 'banana', x: 8, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Define a function, then use it in a loop!\nhop = () ->\n  step 2\n# Call hop 4 times:\n',
    hint: 'Use for i in [1..4] with hop() inside the loop to collect all 4 bananas.',
    starThresholds: [5, 4, 3],
    requiredCommands: ['->', 'for'],
    assessments: [
      { type: 'multiple-choice', question: 'What does step -3 do?', options: ['Moves forward 3', 'Moves backward 3', 'Causes an error', 'Turns around'], correct: 1 },
      { type: 'multiple-choice', question: 'What is debugging?', options: ['Adding bugs to code', 'Finding and fixing mistakes in code', 'Deleting all code', 'Running code faster'], correct: 1 },
    ],
  },

  // =====================================================
  // LESSON 19: Fake It (functions calling functions)
  // =====================================================

  {
    id: 7,
    part: 2,
    lesson: 19,
    lessonTitle: 'Fake It \'Til You Make It',
    title: 'Function Chain',
    concept: 'functions calling functions',
    gridWidth: 7,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 6, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# One function can call another!\ngoto = (a) ->\n  turnTo a\n  step distanceTo a\n\nmoveAndGet = (a) ->\n  goto a\n\nmoveAndGet banana\n',
    hint: 'moveAndGet calls goto, which calls turnTo and step. This is called a "function chain".',
    starThresholds: [7, 5, 4],
    requiredCommands: ['->'],
    lessonContent: '<h3>Functions Calling Functions</h3><p>A function can <b>call other functions</b> inside its body. This creates a <b>call stack</b> -- a chain of function calls.</p><pre>goto = (a) ->\n  turnTo a\n  step distanceTo a\n\ncollect = (a) ->\n  goto a\n  grab()</pre><p><b>Pseudo-code</b> is a way to plan your algorithm in plain language before writing real code.</p>',
  },

  {
    id: 8,
    part: 2,
    lesson: 19,
    lessonTitle: 'Fake It \'Til You Make It',
    title: 'Zigzag Builder',
    concept: 'pattern functions',
    gridWidth: 7,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 2 },
      { type: 'banana', x: 4, y: 4 },
      { type: 'banana', x: 6, y: 6 },
    ],
    autoGrab: true,
    starterCode: '# Define a zigzag step function!\nzigStep = () ->\n  step 2\n  turn right\n  step 2\n  turn left\n# Call it 3 times:\n',
    hint: 'Call zigStep() three times, or use for i in [1..3] / zigStep().',
    starThresholds: [8, 6, 4],
    requiredCommands: ['->'],
  },

  {
    id: 9,
    part: 2,
    lesson: 19,
    lessonTitle: 'Fake It \'Til You Make It',
    title: 'Collect All',
    concept: 'call stack',
    gridWidth: 9,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 1 },
      { type: 'banana', x: 5, y: 1 },
      { type: 'banana', x: 8, y: 1 },
    ],
    autoGrab: true,
    starterCode: '# getNext uses turnTo and step\n# collectAll uses getNext in a loop\ngetNext = (b) ->\n  turnTo b\n  step distanceTo b\n\n# Now loop through all bananas!\nfor b in bananas\n  getNext b\n',
    hint: 'getNext navigates to one banana. The for loop calls it for each banana in the array.',
    starThresholds: [7, 5, 4],
    requiredCommands: ['->', 'for'],
    assessments: [
      { type: 'multiple-choice', question: 'What is a call stack?', options: ['A list of bananas', 'A chain of functions calling each other', 'A type of loop', 'A debugging tool'], correct: 1 },
      { type: 'true-false', question: 'A function can only call built-in functions like step and turn.', correct: false, feedback: 'Functions can call ANY function, including ones you defined!' },
    ],
  },

  // =====================================================
  // LESSON 20: Until (until loops, near)
  // =====================================================

  {
    id: 10,
    part: 2,
    lesson: 20,
    lessonTitle: 'It Ain\'t Over Until It\'s Over',
    title: 'Walk Until Near',
    concept: 'until loops',
    gridWidth: 8,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 6, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# until loops repeat UNTIL a condition is true\n# near(banana) is true when next to the banana\nuntil near banana\n  step 1\n',
    hint: 'The until loop checks near(banana) each time. While false, it runs step 1. When true, it stops and the monkey collects the banana!',
    starThresholds: [4, 3, 3],
    requiredCommands: ['until'],
    lessonContent: '<h3>Until Loops</h3><p>An <b>until loop</b> repeats code until a condition becomes true:</p><pre>until near banana\n  step 1</pre><p><code>near(target)</code> returns true when the monkey is next to the target (1 step away).</p><p>Be careful! If the condition never becomes true, you get an <b>infinite loop</b> and the program crashes!</p>',
  },

  {
    id: 11,
    part: 2,
    lesson: 20,
    lessonTitle: 'It Ain\'t Over Until It\'s Over',
    title: 'Unknown Distance',
    concept: 'near() function',
    gridWidth: 10,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 8, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# You don\'t know exactly how far the banana is!\n# Use until near to walk there step by step\n',
    hint: 'turnTo banana first, then until near banana / step 1. This works regardless of distance!',
    starThresholds: [4, 3, 3],
    requiredCommands: ['until', 'near'],
  },

  {
    id: 12,
    part: 2,
    lesson: 20,
    lessonTitle: 'It Ain\'t Over Until It\'s Over',
    title: 'Two Until Loops',
    concept: 'multiple until loops',
    gridWidth: 7,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 6, y: 0 },
      { type: 'banana', x: 6, y: 6 },
    ],
    autoGrab: true,
    starterCode: '# Collect both bananas using until loops!\nturnTo bananas[0]\nuntil near bananas[0]\n  step 1\n# Now get the second one!\n',
    hint: 'After the first until loop, turnTo bananas[1] and use another until near loop.',
    starThresholds: [10, 8, 7],
    requiredCommands: ['until'],
    assessments: [
      { type: 'multiple-choice', question: 'What does near(banana) return?', options: ['The distance to the banana', 'true if next to the banana, false otherwise', 'The banana object', 'Nothing'], correct: 1 },
      { type: 'multiple-choice', question: 'What happens if an until loop\'s condition is never true?', options: ['The program ends normally', 'It runs forever (infinite loop)', 'It skips the loop', 'It throws a syntax error'], correct: 1 },
    ],
  },

  // =====================================================
  // LESSON 21: Cut to the Chase (until + functions)
  // =====================================================

  {
    id: 13,
    part: 2,
    lesson: 21,
    lessonTitle: 'Cut to the Chase',
    title: 'Chase the Banana',
    concept: 'chase function',
    gridWidth: 7,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 0, y: 6 },
      { type: 'banana', x: 6, y: 6 },
      { type: 'banana', x: 6, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Define a chase function!\nchase = (b) ->\n  turnTo b\n  until near b\n    step 1\n\n# Use it:\nfor b in bananas\n  chase b\n',
    hint: 'chase combines turnTo and until near into a reusable function. Route: down to (0,6), right to (6,6), up to (6,0).',
    starThresholds: [7, 5, 4],
    requiredCommands: ['until', '->'],
    lessonContent: '<h3>Chase Pattern</h3><p>Combining <code>until</code> with functions creates powerful patterns:</p><pre>chase = (b) ->\n  turnTo b\n  until near b\n    step 1</pre><p>This <b>chase</b> function works for any target at any distance! Think about <b>runtime efficiency</b> -- using <code>step distanceTo b</code> is faster but <code>until near</code> is more flexible.</p>',
  },

  {
    id: 14,
    part: 2,
    lesson: 21,
    lessonTitle: 'Cut to the Chase',
    title: 'Efficient Chase',
    concept: 'runtime efficiency',
    gridWidth: 9,
    gridHeight: 9,
    monkeyStart: { x: 4, y: 4, direction: 0 },
    entities: [
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 8, y: 0 },
      { type: 'banana', x: 8, y: 8 },
      { type: 'banana', x: 0, y: 8 },
    ],
    autoGrab: true,
    starterCode: '# Collect all 4 bananas!\nchase = (b) ->\n  turnTo b\n  until near b\n    step 1\n\n',
    hint: 'for b in bananas / chase b works! Route: up to (4,0), right to (8,0), down to (8,8), left to (0,8).',
    starThresholds: [10, 8, 6],
    requiredCommands: ['until', 'for'],
  },

  {
    id: 15,
    part: 2,
    lesson: 21,
    lessonTitle: 'Cut to the Chase',
    title: 'Banana Trail',
    concept: 'chase in loops',
    gridWidth: 9,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'banana', x: 1, y: 2 },
      { type: 'banana', x: 2, y: 2 },
      { type: 'banana', x: 3, y: 2 },
      { type: 'banana', x: 4, y: 2 },
      { type: 'banana', x: 4, y: 3 },
      { type: 'banana', x: 4, y: 4 },
      { type: 'banana', x: 5, y: 4 },
      { type: 'banana', x: 6, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# 8 bananas in an L-shape trail!\nchase = (b) ->\n  turnTo b\n  until near b\n    step 1\n\n# Collect them all:\n',
    hint: 'for b in bananas / chase b handles any number of bananas in any arrangement!',
    starThresholds: [6, 5, 4],
    requiredCommands: ['until', 'for'],
    assessments: [
      { type: 'multiple-choice', question: 'Which is more runtime-efficient for reaching a banana?', options: ['until near b / step 1', 'step distanceTo b', 'Both are equally efficient', 'Neither works'], correct: 1 },
      { type: 'true-false', question: 'The chase function can be used for any target, not just bananas.', correct: true, feedback: 'Correct! chase works with any object that has x and y coordinates.' },
    ],
  },

  // =====================================================
  // LESSON 22: Wait for It (cat, sleeping, wait)
  // =====================================================

  {
    id: 16,
    part: 2,
    lesson: 22,
    lessonTitle: 'Wait for It...',
    title: 'Sleeping Cat',
    concept: 'cat.sleeping() / wait()',
    gridWidth: 8,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'cat', x: 3, y: 0, isActor: true, direction: 0, sleeping: true, wakesAt: 3 },
      { type: 'banana', x: 7, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# The cat blocks the path! Wait for it to move.\n# cat.sleeping() is true while the cat sleeps\n# wait() lets time pass\nuntil not cat.sleeping()\n  wait()\nstep 7\n',
    hint: 'Use until not cat.sleeping() / wait() to wait for the cat to wake up. Then walk past to the banana.',
    starThresholds: [5, 4, 4],
    requiredCommands: ['wait', 'until'],
    lessonContent: '<h3>Wait for It!</h3><p>Some characters have <b>states</b> that change over time. The cat sleeps and then wakes up!</p><pre>until not cat.sleeping()\n  wait()</pre><p><code>cat.sleeping()</code> returns true while the cat is asleep. <code>wait()</code> lets time pass. Once the cat wakes up, it moves aside and you can pass!</p>',
  },

  {
    id: 17,
    part: 2,
    lesson: 22,
    lessonTitle: 'Wait for It...',
    title: 'Patient Monkey',
    concept: 'wait with obstacles',
    gridWidth: 8,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'cat', x: 3, y: 2, isActor: true, direction: 0, sleeping: true, wakesAt: 4 },
      { type: 'bush', x: 3, y: 0 },
      { type: 'bush', x: 3, y: 1 },
      { type: 'bush', x: 3, y: 3 },
      { type: 'bush', x: 3, y: 4 },
      { type: 'banana', x: 7, y: 2 },
    ],
    autoGrab: true,
    starterCode: '# The only way past is through the cat!\n# Walk up to it, wait, then continue\n',
    hint: 'Step toward the cat, then wait for it to wake up. The bushes block all other paths!',
    starThresholds: [8, 6, 5],
    requiredCommands: ['wait'],
  },

  {
    id: 18,
    part: 2,
    lesson: 22,
    lessonTitle: 'Wait for It...',
    title: 'Two Cats',
    concept: 'functions + wait',
    gridWidth: 10,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'cat', x: 3, y: 0, isActor: false, sleeping: true, wakesAt: 2 },
      { type: 'cat', x: 6, y: 0, isActor: false, sleeping: true, wakesAt: 5 },
      { type: 'banana', x: 9, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Two cats blocking the way!\n# Define a function to handle each one\nwaitAndPass = () ->\n  wait()\n  wait()\n  step 3\n\n',
    hint: 'Call waitAndPass() twice -- once for each cat. Or define a smarter function!',
    starThresholds: [8, 6, 5],
    requiredCommands: ['wait', '->'],
    assessments: [
      { type: 'multiple-choice', question: 'What does wait() do?', options: ['Stops the program', 'Lets time pass by one tick', 'Makes the monkey sleep', 'Resets the puzzle'], correct: 1 },
      { type: 'true-false', question: 'cat.sleeping() returns true forever.', correct: false, feedback: 'The cat eventually wakes up! sleeping() becomes false after enough wait() calls.' },
    ],
  },

  // =====================================================
  // LESSON 23: Act the Goat (if, goat, frozen)
  // =====================================================

  {
    id: 19,
    part: 2,
    lesson: 23,
    lessonTitle: 'Act the Goat',
    title: 'Ice Breaker',
    concept: 'goat.hit() / frozen',
    gridWidth: 8,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'goat', x: 1, y: 1, isActor: true, direction: 0 },
      { type: 'banana', x: 5, y: 1, frozen: true },
    ],
    autoGrab: true,
    starterCode: '# The banana is frozen! The goat can break the ice.\n# goat.step moves the goat\n# goat.hit(banana) breaks the ice\ngoat.step 4\ngoat.hit banana\n# Now walk the monkey to collect it!\n',
    hint: 'After the goat breaks the ice, step 5 to reach and collect the banana.',
    starThresholds: [5, 4, 3],
    requiredCommands: ['goat'],
    lessonContent: '<h3>Conditionals</h3><p><code>if</code> lets you run code only when a condition is true:</p><pre>if banana.frozen()\n  goat.goto banana\n  goat.hit banana</pre><p>The <b>goat</b> is a new character! <code>goat.step</code>, <code>goat.turnTo</code>, and <code>goat.goto</code> move the goat. <code>goat.hit(banana)</code> breaks frozen bananas!</p><p><code>banana.frozen()</code> returns true if the banana is frozen.</p>',
  },

  {
    id: 20,
    part: 2,
    lesson: 23,
    lessonTitle: 'Act the Goat',
    title: 'If Frozen',
    concept: 'if conditionals',
    gridWidth: 8,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 4, y: 2, frozen: true },
      { type: 'banana', x: 7, y: 2, frozen: false },
    ],
    autoGrab: true,
    starterCode: '# Check if each banana is frozen!\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: 'The if statement only runs goat.hit when the banana is frozen. The monkey always collects afterward.',
    starThresholds: [10, 8, 6],
    requiredCommands: ['if', 'goat'],
  },

  {
    id: 21,
    part: 2,
    lesson: 23,
    lessonTitle: 'Act the Goat',
    title: 'Goat Helper',
    concept: 'if + functions',
    gridWidth: 10,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 3, y: 2, frozen: true },
      { type: 'banana', x: 5, y: 2, frozen: false },
      { type: 'banana', x: 7, y: 2, frozen: true },
      { type: 'banana', x: 9, y: 2, frozen: false },
    ],
    autoGrab: true,
    starterCode: '# Define a function to handle any banana!\nhandleBanana = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  handleBanana b\n',
    hint: 'handleBanana checks if frozen, uses goat if needed, then walks monkey to collect.',
    starThresholds: [12, 10, 6],
    requiredCommands: ['if', '->', 'goat'],
    assessments: [
      { type: 'multiple-choice', question: 'What does goat.hit(banana) do?', options: ['Eats the banana', 'Breaks the ice on a frozen banana', 'Moves the banana', 'Nothing'], correct: 1 },
      { type: 'multiple-choice', question: 'When does the code inside an if statement run?', options: ['Always', 'Never', 'Only when the condition is true', 'Only when the condition is false'], correct: 2 },
    ],
  },

  // =====================================================
  // LESSON 24: Green Banana Sorbet (if-else, green)
  // =====================================================

  {
    id: 22,
    part: 2,
    lesson: 24,
    lessonTitle: 'Green Banana Sorbet',
    title: 'Green or Ripe?',
    concept: 'if-else',
    gridWidth: 7,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 0, green: false },
      { type: 'banana', x: 4, y: 0, green: true },
      { type: 'banana', x: 6, y: 0, green: false },
    ],
    autoGrab: true,
    starterCode: '# Green bananas should be skipped!\n# banana.green() returns true for green ones\nfor b in bananas\n  turnTo b\n  step distanceTo b\n  # Only ripe bananas are collected automatically\n',
    hint: 'Green bananas are automatically skipped during auto-grab. Just walk through all of them!',
    starThresholds: [6, 5, 4],
    lessonContent: '<h3>If-Else</h3><p><code>if-else</code> lets you choose between two actions:</p><pre>if banana.green()\n  # skip it\nelse\n  # collect it</pre><p><code>banana.green()</code> returns true for unripe green bananas. The monkey should skip green bananas!</p>',
  },

  {
    id: 23,
    part: 2,
    lesson: 24,
    lessonTitle: 'Green Banana Sorbet',
    title: 'Sorting Bananas',
    concept: 'if-else decisions',
    gridWidth: 9,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'banana', x: 2, y: 1, green: false },
      { type: 'banana', x: 4, y: 1, green: true },
      { type: 'banana', x: 6, y: 1, green: false },
      { type: 'banana', x: 8, y: 1, green: true },
    ],
    autoGrab: true,
    starterCode: '# Walk past all bananas!\n# Ripe ones are collected, green ones are skipped\nfor b in bananas\n  turnTo b\n  step distanceTo b\n',
    hint: 'The monkey automatically skips green bananas. Just visit every banana in the loop.',
    starThresholds: [6, 5, 4],
  },

  {
    id: 24,
    part: 2,
    lesson: 24,
    lessonTitle: 'Green Banana Sorbet',
    title: 'Green Detour',
    concept: 'if-else with goat',
    gridWidth: 9,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 3, y: 2, green: true },
      { type: 'banana', x: 5, y: 2, green: false },
      { type: 'banana', x: 7, y: 2, frozen: true },
    ],
    autoGrab: true,
    starterCode: '# Different bananas need different handling!\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: 'Frozen bananas need the goat first. Green bananas are skipped automatically. Only ripe ones are collected!',
    starThresholds: [10, 8, 6],
    requiredCommands: ['if'],
    assessments: [
      { type: 'multiple-choice', question: 'What does the else part of if-else do?', options: ['Runs when the condition is true', 'Runs when the condition is false', 'Runs every time', 'Does nothing'], correct: 1 },
      { type: 'true-false', question: 'banana.green() returns true for ripe yellow bananas.', correct: false, feedback: 'green() returns true for GREEN (unripe) bananas, not yellow ones!' },
    ],
  },

  // =====================================================
  // LESSON 25: If All Else Fails (if-else practice)
  // =====================================================

  {
    id: 25,
    part: 2,
    lesson: 25,
    lessonTitle: 'If All Else Fails',
    title: 'Conditional Function',
    concept: 'if-else in functions',
    gridWidth: 8,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 3, y: 2, frozen: true },
      { type: 'banana', x: 5, y: 2, green: true },
      { type: 'banana', x: 7, y: 2, frozen: false, green: false },
    ],
    autoGrab: true,
    starterCode: '# Handle each type differently!\nhandle = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  handle b\n',
    hint: 'The function handles frozen (goat breaks ice), green (auto-skipped), and ripe (auto-collected).',
    starThresholds: [10, 8, 6],
    requiredCommands: ['if', '->'],
    lessonContent: '<h3>Practice If-Else</h3><p>You can put <code>if-else</code> inside functions to handle different cases:</p><pre>handle = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  if b.green()\n    # skip it\n  else\n    goto b</pre><p>Multiple conditions can be checked one after another. The code handles frozen, green, and ripe bananas differently!</p>',
  },

  {
    id: 26,
    part: 2,
    lesson: 25,
    lessonTitle: 'If All Else Fails',
    title: 'Multi-Condition',
    concept: 'multiple if checks',
    gridWidth: 10,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 2, frozen: true },
      { type: 'banana', x: 4, y: 2, green: true },
      { type: 'banana', x: 6, y: 2, frozen: false, green: false },
      { type: 'banana', x: 8, y: 2, frozen: true },
    ],
    autoGrab: true,
    starterCode: '# Handle all banana types!\n',
    hint: 'Loop through bananas. Check frozen first (goat.hit), then just walk to each one.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['if', '->'],
  },

  {
    id: 27,
    part: 2,
    lesson: 25,
    lessonTitle: 'If All Else Fails',
    title: 'Decision Maze',
    concept: 'complex conditionals',
    gridWidth: 10,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 3, direction: 0 },
    entities: [
      { type: 'goat', x: 1, y: 3, isActor: true, direction: 0 },
      { type: 'banana', x: 3, y: 3, frozen: true },
      { type: 'banana', x: 5, y: 3, green: false, frozen: false },
      { type: 'banana', x: 7, y: 3, frozen: true },
      { type: 'banana', x: 9, y: 3, green: true },
    ],
    autoGrab: true,
    starterCode: '# Navigate the maze and handle all banana types!\nhandle = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\n',
    hint: 'Use handle for each banana. The bushes mean you need to think about the path!',
    starThresholds: [14, 12, 10],
    requiredCommands: ['if', '->'],
    assessments: [
      { type: 'multiple-choice', question: 'What happens when you use two if statements in a row?', options: ['Only the first runs', 'Only the second runs', 'Both are checked independently', 'It causes an error'], correct: 2 },
      { type: 'true-false', question: 'if-else is better than two separate if statements when the conditions are opposites.', correct: true, feedback: 'Correct! if-else is cleaner when you have two opposite cases.' },
    ],
  },

  // =====================================================
  // LESSON 26: And in the End (AND operator)
  // =====================================================

  {
    id: 28,
    part: 2,
    lesson: 26,
    lessonTitle: 'And in the End',
    title: 'Both Conditions',
    concept: 'and operator',
    gridWidth: 9,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 1, frozen: true, green: false },
      { type: 'banana', x: 4, y: 1, frozen: false, green: true },
      { type: 'banana', x: 6, y: 1, frozen: false, green: false },
      { type: 'banana', x: 8, y: 1, frozen: true, green: false },
    ],
    autoGrab: true,
    starterCode: '# Use "and" to combine two conditions!\n# not b.frozen() and not b.green() means safe to collect\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: '"and" checks two conditions at once. Both must be true. Use it to filter bananas!',
    starThresholds: [10, 8, 6],
    requiredCommands: ['if'],
    lessonContent: '<h3>The AND Operator</h3><p><code>and</code> combines two conditions. Both must be true:</p><pre>if not b.frozen() and not b.green()\n  # safe to collect!</pre><p><b>Truth Table:</b></p><table style="margin:8px 0;border-collapse:collapse;"><tr><th style="border:1px solid #555;padding:4px;">A</th><th style="border:1px solid #555;padding:4px;">B</th><th style="border:1px solid #555;padding:4px;">A and B</th></tr><tr><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;color:#4a4;">true</td></tr><tr><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;color:#a44;">false</td></tr><tr><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;color:#a44;">false</td></tr><tr><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;color:#a44;">false</td></tr></table>',
  },

  {
    id: 29,
    part: 2,
    lesson: 26,
    lessonTitle: 'And in the End',
    title: 'And Truth Table',
    concept: 'and filtering',
    gridWidth: 10,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 1, frozen: true, green: false },
      { type: 'banana', x: 4, y: 1, frozen: false, green: false },
      { type: 'banana', x: 6, y: 1, frozen: false, green: true },
      { type: 'banana', x: 8, y: 1, frozen: true, green: false },
    ],
    autoGrab: true,
    starterCode: '# Break frozen bananas, skip green ones, collect ripe ones!\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: 'The goat breaks frozen ones. Green ones are auto-skipped. Only ripe, unfrozen bananas get collected.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['if', 'for'],
  },

  {
    id: 30,
    part: 2,
    lesson: 26,
    lessonTitle: 'And in the End',
    title: 'And with Functions',
    concept: 'and in functions',
    gridWidth: 10,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 3, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 3, y: 3, frozen: true, green: false },
      { type: 'banana', x: 5, y: 3, frozen: false, green: false },
      { type: 'banana', x: 7, y: 3, frozen: false, green: true },
      { type: 'banana', x: 9, y: 3, frozen: true, green: false },
    ],
    autoGrab: true,
    starterCode: '# Use and inside a function!\nprocess = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  process b\n',
    hint: 'Process each banana: break ice if frozen, then walk to collect.',
    starThresholds: [14, 12, 10],
    requiredCommands: ['if', '->'],
    assessments: [
      { type: 'multiple-choice', question: 'When is "A and B" true?', options: ['When A is true', 'When B is true', 'When BOTH A and B are true', 'When either is true'], correct: 2 },
      { type: 'true-false', question: '"not frozen() and not green()" means the banana is safe to eat.', correct: true, feedback: 'Correct! Both conditions must be true -- not frozen AND not green.' },
    ],
  },

  // =====================================================
  // LESSON 27: Take it or Leave it (OR operator)
  // =====================================================

  {
    id: 31,
    part: 2,
    lesson: 27,
    lessonTitle: 'Take it or Leave it!',
    title: 'Either Way',
    concept: 'or operator',
    gridWidth: 9,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 1, frozen: true, green: false },
      { type: 'banana', x: 4, y: 1, frozen: false, green: true },
      { type: 'banana', x: 6, y: 1, frozen: false, green: false },
      { type: 'banana', x: 8, y: 1, frozen: false, green: false },
    ],
    autoGrab: true,
    starterCode: '# "or" is true when at least one condition is true\n# Skip bananas that have ANY problem!\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: '"or" is true if at least one condition is true. b.frozen() or b.green() catches bananas with any issue.',
    starThresholds: [10, 8, 6],
    requiredCommands: ['if'],
    lessonContent: '<h3>The OR Operator</h3><p><code>or</code> is true when <b>at least one</b> condition is true:</p><pre>if b.frozen() or b.green()\n  # has a problem!</pre><p><b>Truth Table:</b></p><table style="margin:8px 0;border-collapse:collapse;"><tr><th style="border:1px solid #555;padding:4px;">A</th><th style="border:1px solid #555;padding:4px;">B</th><th style="border:1px solid #555;padding:4px;">A or B</th></tr><tr><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;color:#4a4;">true</td></tr><tr><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;color:#4a4;">true</td></tr><tr><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;">true</td><td style="border:1px solid #555;padding:4px;color:#4a4;">true</td></tr><tr><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;">false</td><td style="border:1px solid #555;padding:4px;color:#a44;">false</td></tr></table>',
  },

  {
    id: 32,
    part: 2,
    lesson: 27,
    lessonTitle: 'Take it or Leave it!',
    title: 'Or Truth Table',
    concept: 'or filtering',
    gridWidth: 10,
    gridHeight: 3,
    monkeyStart: { x: 0, y: 1, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 1, frozen: false, green: false },
      { type: 'banana', x: 4, y: 1, frozen: true, green: true },
      { type: 'banana', x: 6, y: 1, frozen: true, green: false },
      { type: 'banana', x: 8, y: 1, frozen: false, green: false },
    ],
    autoGrab: true,
    starterCode: '# Break all frozen bananas, then collect ripe ones\nfor b in bananas\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n',
    hint: 'Process each banana in order. Goat breaks frozen ones, green ones are skipped, ripe ones are collected.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['if', 'for'],
  },

  {
    id: 33,
    part: 2,
    lesson: 27,
    lessonTitle: 'Take it or Leave it!',
    title: 'Or in Action',
    concept: 'or with functions',
    gridWidth: 10,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 3, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 3, frozen: true, green: false },
      { type: 'banana', x: 4, y: 3, frozen: false, green: false },
      { type: 'banana', x: 6, y: 3, frozen: false, green: true },
      { type: 'banana', x: 8, y: 3, frozen: true, green: false },
      { type: 'banana', x: 9, y: 3, frozen: false, green: false },
    ],
    autoGrab: true,
    starterCode: '# Combine or with functions!\nprocess = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  process b\n',
    hint: 'Process handles everything: frozen get goat treatment, green are skipped, ripe are collected.',
    starThresholds: [14, 12, 10],
    requiredCommands: ['if', '->'],
    assessments: [
      { type: 'multiple-choice', question: 'When is "A or B" true?', options: ['Only when both are true', 'When at least one is true', 'Only when A is true', 'Never'], correct: 1 },
      { type: 'multiple-choice', question: '"not (A or B)" is the same as:', options: ['not A or not B', 'not A and not B', 'A and B', 'A or B'], correct: 1 },
    ],
  },

  // =====================================================
  // LESSON 28: Mix and Match (array literals, polymorphism)
  // =====================================================

  {
    id: 34,
    part: 2,
    lesson: 28,
    lessonTitle: 'Mix and Match',
    title: 'Make a List',
    concept: 'array literals',
    gridWidth: 7,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'banana', x: 3, y: 2 },
      { type: 'turtle', x: 3, y: 4, direction: 0 },
      { type: 'banana', x: 6, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# Create your own array with [ ]!\n# targets = [bananas[0], turtle, bananas[1]]\ntargets = [bananas[0], turtle, bananas[1]]\nfor t in targets\n  turnTo t\n  step distanceTo t\n',
    hint: 'Array literals let you make custom lists. Route: right to (3,2), down to (3,4) turtle, right to (6,4).',
    starThresholds: [8, 6, 5],
    requiredCommands: ['['],
    lessonContent: '<h3>Array Literals</h3><p>You can create custom arrays with <code>[ ]</code>:</p><pre>targets = [banana, turtle, banana]\nfor t in targets\n  turnTo t\n  step distanceTo t</pre><p>Different object types can be in the same array -- this is called <b>polymorphism</b>. As long as objects share actions (like having x/y positions), you can treat them the same way!</p>',
  },

  {
    id: 35,
    part: 2,
    lesson: 28,
    lessonTitle: 'Mix and Match',
    title: 'Mixed Targets',
    concept: 'mixed-type arrays',
    gridWidth: 9,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 3, direction: 0 },
    entities: [
      { type: 'banana', x: 4, y: 3 },
      { type: 'banana', x: 4, y: 0 },
      { type: 'turtle', x: 4, y: 6, direction: 0 },
      { type: 'banana', x: 8, y: 6 },
    ],
    autoGrab: true,
    starterCode: '# Visit targets in the best order!\n# Create an array with the optimal route\n',
    hint: 'Route: right to (4,3), up to (4,0), down to (4,6) turtle, right to (8,6). Use [target1, target2, ...] to set the order.',
    starThresholds: [10, 8, 6],
    requiredCommands: ['[', 'for'],
  },

  {
    id: 36,
    part: 2,
    lesson: 28,
    lessonTitle: 'Mix and Match',
    title: 'Custom Route',
    concept: 'route planning',
    gridWidth: 9,
    gridHeight: 9,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 3, y: 0 },
      { type: 'banana', x: 3, y: 8 },
      { type: 'banana', x: 8, y: 8 },
      { type: 'banana', x: 8, y: 0 },
      { type: 'bush', x: 4, y: 0 },
      { type: 'bush', x: 4, y: 1 },
      { type: 'bush', x: 4, y: 2 },
      { type: 'bush', x: 4, y: 3 },
    ],
    autoGrab: true,
    starterCode: '# Plan the best route around the bushes!\nchase = (b) ->\n  turnTo b\n  until near b\n    step 1\n\n# Create your route array:\n',
    hint: 'Route: right to (3,0), down to (3,8), right to (8,8), up to (8,0). The bushes block column 4!',
    starThresholds: [12, 10, 8],
    requiredCommands: ['['],
    assessments: [
      { type: 'multiple-choice', question: 'What does [banana, turtle] create?', options: ['A function', 'An array with two elements', 'A loop', 'An error'], correct: 1 },
      { type: 'true-false', question: 'An array can contain different types of objects.', correct: true, feedback: 'Correct! This is called polymorphism -- different types in one array.' },
    ],
  },

  // =====================================================
  // LESSON 29: Fashion Alert (penguins, and/or with if)
  // =====================================================

  {
    id: 37,
    part: 2,
    lesson: 29,
    lessonTitle: 'Fashion Alert!',
    title: 'Penguin Parade',
    concept: 'hasGlasses / hasBowTie',
    gridWidth: 9,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'penguin', x: 2, y: 0, hasGlasses: true, hasBowTie: false },
      { type: 'penguin', x: 4, y: 0, hasGlasses: false, hasBowTie: true },
      { type: 'penguin', x: 6, y: 0, hasGlasses: true, hasBowTie: false },
      { type: 'banana', x: 3, y: 2 },
      { type: 'banana', x: 5, y: 2 },
      { type: 'banana', x: 8, y: 2 },
    ],
    autoGrab: true,
    starterCode: '# Collect all the bananas!\n# The penguins are just watching.\nfor b in bananas\n  turnTo b\n  step distanceTo b\n',
    hint: 'Walk right along row 2 to collect all bananas. The penguins above are just observers!',
    starThresholds: [14, 12, 10],
    requiredCommands: ['if'],
    lessonContent: '<h3>Fashion Alert!</h3><p>Penguins wear accessories! Check what they\'re wearing:</p><pre>if p.hasGlasses()\n  # this penguin wears glasses!\nif p.hasBowTie()\n  # this one has a bow tie!</pre><p>Combine with <code>and</code>/<code>or</code> to find penguins with specific combinations:</p><pre>if p.hasGlasses() and p.hasBowTie()\n  # extra fancy penguin!</pre>',
  },

  {
    id: 38,
    part: 2,
    lesson: 29,
    lessonTitle: 'Fashion Alert!',
    title: 'Fancy Penguins',
    concept: 'and with penguins',
    gridWidth: 9,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'penguin', x: 2, y: 2, hasGlasses: true, hasBowTie: true },
      { type: 'penguin', x: 4, y: 2, hasGlasses: true, hasBowTie: false },
      { type: 'penguin', x: 6, y: 2, hasGlasses: false, hasBowTie: true },
      { type: 'banana', x: 2, y: 2 },
      { type: 'banana', x: 4, y: 2 },
      { type: 'banana', x: 6, y: 2 },
      { type: 'banana', x: 8, y: 2 },
    ],
    autoGrab: true,
    starterCode: '# Find the fanciest penguin (glasses AND bowtie)!\nfor p in penguins\n  if p.hasGlasses() and p.hasBowTie()\n    turnTo p\n    step distanceTo p\n',
    hint: 'Only the penguin with BOTH glasses AND bowtie is the fancy one. Use "and" to check both! All bananas are on row 2.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['and'],
  },

  {
    id: 39,
    part: 2,
    lesson: 29,
    lessonTitle: 'Fashion Alert!',
    title: 'Fashion Filter',
    concept: 'or with penguins',
    gridWidth: 9,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 4, direction: 0 },
    entities: [
      { type: 'penguin', x: 2, y: 2, hasGlasses: true, hasBowTie: false },
      { type: 'penguin', x: 4, y: 2, hasGlasses: false, hasBowTie: false },
      { type: 'penguin', x: 6, y: 2, hasGlasses: false, hasBowTie: true },
      { type: 'banana', x: 2, y: 4 },
      { type: 'banana', x: 6, y: 4 },
      { type: 'banana', x: 8, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# At least one accessory required!\n# Use "or" to find penguins with glasses OR bowtie\nfor p in penguins\n  if p.hasGlasses() or p.hasBowTie()\n    turnTo p\n    step distanceTo p\n',
    hint: 'Use "or" to find penguins with at least one accessory. Two out of three penguins qualify! Bananas are all on row 4.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['or'],
    assessments: [
      { type: 'multiple-choice', question: 'p.hasGlasses() and p.hasBowTie() is true when:', options: ['Penguin has glasses', 'Penguin has bowtie', 'Penguin has BOTH', 'Penguin has EITHER'], correct: 2 },
      { type: 'multiple-choice', question: 'p.hasGlasses() or p.hasBowTie() is true when:', options: ['Penguin has both', 'Penguin has at least one accessory', 'Penguin has no accessories', 'Never'], correct: 1 },
    ],
  },

  // =====================================================
  // LESSON 30: Loops are Fun (review loops)
  // =====================================================

  {
    id: 40,
    part: 2,
    lesson: 30,
    lessonTitle: 'Loops are Fun',
    title: 'Loop Review: For',
    concept: 'for i in [1..n]',
    gridWidth: 9,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 1, y: 0 },
      { type: 'banana', x: 2, y: 0 },
      { type: 'banana', x: 3, y: 0 },
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 5, y: 0 },
      { type: 'banana', x: 6, y: 0 },
      { type: 'banana', x: 7, y: 0 },
      { type: 'banana', x: 8, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Collect all 8 bananas with a simple loop!\n# for i in [1..8]\n#   step 1\n',
    hint: 'for i in [1..8] repeats 8 times. step 1 inside collects one banana each time.',
    starThresholds: [4, 3, 2],
    requiredCommands: ['for'],
    lessonContent: '<h3>Loop Review</h3><p>Let\'s review all three loop types:</p><p><b>For range:</b> <code>for i in [1..n]</code> repeats n times</p><p><b>For-in:</b> <code>for b in bananas</code> iterates through a collection</p><p><b>Until:</b> <code>until condition</code> repeats until something becomes true</p><p>Each type is best for different situations!</p>',
  },

  {
    id: 41,
    part: 2,
    lesson: 30,
    lessonTitle: 'Loops are Fun',
    title: 'Loop Review: Until',
    concept: 'until loops',
    gridWidth: 9,
    gridHeight: 9,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 8, y: 8 },
      { type: 'bush', x: 4, y: 0 },
      { type: 'bush', x: 4, y: 1 },
      { type: 'bush', x: 4, y: 2 },
      { type: 'bush', x: 4, y: 3 },
    ],
    autoGrab: true,
    starterCode: '# Use until loops to navigate!\n# Go down to row 4, then right past the bushes\n',
    hint: 'Turn down, use until to walk past the bushes, then turn right and until near banana.',
    starThresholds: [10, 8, 6],
    requiredCommands: ['until'],
  },

  {
    id: 42,
    part: 2,
    lesson: 30,
    lessonTitle: 'Loops are Fun',
    title: 'Loop Review: For-In',
    concept: 'for..in arrays',
    gridWidth: 9,
    gridHeight: 9,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 8, y: 0 },
      { type: 'banana', x: 8, y: 4 },
      { type: 'banana', x: 8, y: 8 },
      { type: 'banana', x: 4, y: 8 },
      { type: 'banana', x: 0, y: 8 },
      { type: 'banana', x: 0, y: 4 },
    ],
    autoGrab: true,
    starterCode: '# Use for-in with chase!\nchase = (b) ->\n  turnTo b\n  until near b\n    step 1\n\nfor b in bananas\n  chase b\n',
    hint: 'chase + for-in handles any banana arrangement. 7 bananas around the perimeter, each cardinal from the previous!',
    starThresholds: [8, 6, 4],
    requiredCommands: ['for'],
    assessments: [
      { type: 'multiple-choice', question: 'Which loop type is best when you don\'t know the exact distance?', options: ['for i in [1..n]', 'until near target', 'for b in bananas', 'All work equally well'], correct: 1 },
      { type: 'multiple-choice', question: 'Which loop type is best for visiting every item in a collection?', options: ['for i in [1..n]', 'until near target', 'for b in bananas', 'while true'], correct: 2 },
    ],
  },

  // =====================================================
  // LESSON 31: What's the Conditional? (review conditionals)
  // =====================================================

  {
    id: 43,
    part: 2,
    lesson: 31,
    lessonTitle: 'What\'s the Conditional?',
    title: 'Conditional Review: If',
    concept: 'if review',
    gridWidth: 10,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 2, frozen: true },
      { type: 'banana', x: 4, y: 2, frozen: false },
      { type: 'banana', x: 6, y: 2, frozen: true },
      { type: 'banana', x: 8, y: 2, frozen: false },
    ],
    autoGrab: true,
    starterCode: '# Review: use if to handle frozen bananas\n',
    hint: 'Loop through bananas. If frozen, use goat. Then walk monkey to collect.',
    starThresholds: [12, 10, 8],
    requiredCommands: ['if'],
    lessonContent: '<h3>Conditional Review</h3><p>Let\'s review all conditional tools:</p><p><b>if:</b> Run code when a condition is true</p><p><b>if-else:</b> Choose between two paths</p><p><b>and:</b> Both conditions must be true</p><p><b>or:</b> At least one must be true</p><p><b>not:</b> Reverses a condition</p>',
  },

  {
    id: 44,
    part: 2,
    lesson: 31,
    lessonTitle: 'What\'s the Conditional?',
    title: 'Conditional Review: And/Or',
    concept: 'and/or review',
    gridWidth: 10,
    gridHeight: 5,
    monkeyStart: { x: 0, y: 2, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 2, frozen: true, green: false },
      { type: 'banana', x: 4, y: 2, frozen: false, green: true },
      { type: 'banana', x: 6, y: 2, frozen: false, green: false },
      { type: 'banana', x: 8, y: 2, frozen: true, green: false },
    ],
    autoGrab: true,
    starterCode: '# Handle all types: frozen, green, and ripe!\nprocess = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  process b\n',
    hint: 'Frozen bananas need goat.hit first. Green are auto-skipped. Ripe are auto-collected.',
    starThresholds: [14, 12, 10],
    requiredCommands: ['if', '->'],
  },

  {
    id: 45,
    part: 2,
    lesson: 31,
    lessonTitle: 'What\'s the Conditional?',
    title: 'Mega Conditional',
    concept: 'all conditionals',
    gridWidth: 11,
    gridHeight: 7,
    monkeyStart: { x: 0, y: 3, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 3, frozen: true },
      { type: 'banana', x: 4, y: 3, frozen: false, green: false },
      { type: 'banana', x: 6, y: 3, green: true },
      { type: 'banana', x: 8, y: 3, frozen: true },
      { type: 'banana', x: 10, y: 3, frozen: false, green: false },
      { type: 'bush', x: 5, y: 0 },
      { type: 'bush', x: 5, y: 1 },
      { type: 'bush', x: 5, y: 2 },
    ],
    autoGrab: true,
    starterCode: '# Use everything: if, and/or, functions, loops!\nprocess = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  process b\n',
    hint: 'Break the problem down: handle frozen bananas with the goat, skip green, collect ripe.',
    starThresholds: [16, 14, 10],
    requiredCommands: ['if', '->'],
    assessments: [
      { type: 'multiple-choice', question: 'Which conditional checks TWO conditions at once?', options: ['if', 'else', 'and / or', 'not'], correct: 2 },
      { type: 'true-false', question: 'You can combine loops, functions, and conditionals in the same code.', correct: true, feedback: 'Correct! Real programs combine all these tools together!' },
    ],
  },

  // =====================================================
  // LESSON 32: Stars Party (optimization)
  // =====================================================

  {
    id: 46,
    part: 2,
    lesson: 32,
    lessonTitle: 'Stars Party!',
    title: 'Speed Run',
    concept: 'code efficiency',
    gridWidth: 11,
    gridHeight: 1,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 1, y: 0 },
      { type: 'banana', x: 2, y: 0 },
      { type: 'banana', x: 3, y: 0 },
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 5, y: 0 },
      { type: 'banana', x: 6, y: 0 },
      { type: 'banana', x: 7, y: 0 },
      { type: 'banana', x: 8, y: 0 },
      { type: 'banana', x: 9, y: 0 },
      { type: 'banana', x: 10, y: 0 },
    ],
    autoGrab: true,
    starterCode: '# Get 3 stars! Shortest code wins.\n# Can you do it in 2 lines?\n',
    hint: 'for i in [1..10] / step 1 -- just 2 lines!',
    starThresholds: [4, 3, 2],
    lessonContent: '<h3>Stars Party!</h3><p>Time to optimize! Getting <b>3 stars</b> means writing the shortest code possible.</p><p>Tips for shorter code:</p><ul><li>Use loops instead of repeating lines</li><li>Use functions to avoid duplicate code</li><li>Use <code>for b in bananas</code> with <code>chase</code> for any arrangement</li><li><code>step distanceTo b</code> is shorter than an until loop</li></ul>',
  },

  {
    id: 47,
    part: 2,
    lesson: 32,
    lessonTitle: 'Stars Party!',
    title: 'Optimize This',
    concept: 'optimization',
    gridWidth: 9,
    gridHeight: 9,
    monkeyStart: { x: 0, y: 0, direction: 0 },
    entities: [
      { type: 'banana', x: 4, y: 0 },
      { type: 'banana', x: 8, y: 0 },
      { type: 'banana', x: 8, y: 4 },
      { type: 'banana', x: 8, y: 8 },
      { type: 'banana', x: 4, y: 8 },
      { type: 'banana', x: 0, y: 8 },
    ],
    autoGrab: true,
    starterCode: '# Find the most efficient solution!\n# Use functions and loops\n',
    hint: 'for b in bananas / turnTo b / step distanceTo b -- visit them in array order around the edge.',
    starThresholds: [8, 6, 4],
  },

  {
    id: 48,
    part: 2,
    lesson: 32,
    lessonTitle: 'Stars Party!',
    title: 'Grand Finale',
    concept: 'everything combined',
    gridWidth: 11,
    gridHeight: 9,
    monkeyStart: { x: 0, y: 4, direction: 0 },
    entities: [
      { type: 'goat', x: 0, y: 0, isActor: true, direction: 0 },
      { type: 'banana', x: 2, y: 4, frozen: true },
      { type: 'banana', x: 4, y: 4, frozen: false, green: false },
      { type: 'banana', x: 4, y: 6, frozen: false, green: true },
      { type: 'banana', x: 8, y: 6, frozen: true },
      { type: 'banana', x: 8, y: 4, frozen: false, green: false },
      { type: 'banana', x: 10, y: 4, frozen: false, green: false },
      { type: 'bush', x: 5, y: 3 },
      { type: 'bush', x: 5, y: 4 },
      { type: 'bush', x: 5, y: 5 },
    ],
    autoGrab: true,
    starterCode: '# The ULTIMATE puzzle! Use EVERYTHING you learned.\n# Functions, loops, conditionals, and/or...\nprocess = (b) ->\n  if b.frozen()\n    goat.goto b\n    goat.hit b\n  turnTo b\n  step distanceTo b\n\nfor b in bananas\n  process b\n',
    hint: 'Route: right to (2,4), (4,4), down to (4,6), right to (8,6), up to (8,4), right to (10,4). Process handles frozen+goat, green is auto-skipped, ripe is auto-collected.',
    starThresholds: [16, 12, 8],
    requiredCommands: ['if', '->', 'for'],
    assessments: [
      { type: 'multiple-choice', question: 'What is the best way to make code shorter?', options: ['Delete comments', 'Use loops and functions', 'Remove all whitespace', 'Use shorter variable names'], correct: 1 },
      { type: 'multiple-choice', question: 'Which approach collects scattered bananas most efficiently?', options: ['step to each one individually', 'for b in bananas with turnTo and step distanceTo', 'until near each banana', 'Random walking'], correct: 1 },
      { type: 'true-false', question: 'You completed Coding Adventure Part 2!', correct: true, feedback: 'Congratulations! You\'ve mastered functions, loops, conditionals, and logic operators!' },
    ],
  },
];

export default part2;
